# vim:ft=yaml.ansible:
---
- name: Git | Download delta themes
  get_url:
    url: https://raw.githubusercontent.com/dandavison/delta/master/themes.gitconfig
    dest: "{{ user_data_dir }}/delta-themes.gitconfig"

- name: Git | Install delta diff tool
  ansible.builtin.apt:
    deb: https://github.com/dandavison/delta/releases/download/0.15.1/git-delta_0.15.1_amd64.deb
    state: present
  become: true

- name: Git | Create config dir
  file:
    path: "{{ user_config_dir }}/gitconfig"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    state: directory

- name: Git | Install personal gitconfig
  template:
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    src: roles/common/templates/gitconfig.j2
    dest: "{{ user_config_dir }}/gitconfig/personal"

# - name: Git | Install current work gitconfig
#  copy:
#    owner: "{{ ansible_user_id }}"
#    group: "{{ ansible_user_gid }}"
#    src: roles/common/files/current-work-gitconfig
#    dest: "{{ user_config_dir }}/gitconfig/work"
